# ML-Server-Manager Development Environment - Worker Node
# 开发模式：仅运行 code-server
# worker 在本地以热重载方式运行 (air)
#
# Usage (从项目根目录):
#   docker compose -f infra/dev/worker.yml up -d
#   make dev-worker  # 或使用 Makefile

services:
  # Code-Server (VS Code in Browser)
  code-server:
    image: codercom/code-server:latest
    container_name: mlsm-dev-codeserver
    restart: unless-stopped
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      # 开发模式禁用密码
      CS_DISABLE_GETTING_STARTED_OVERRIDE: "true"
      # 显式清除代理设置，避免扩展安装问题
      HTTP_PROXY: ""
      HTTPS_PROXY: ""
      http_proxy: ""
      https_proxy: ""
    volumes:
      # 挂载项目目录 (与 worker 共享)
      - ../../data/projects:/home/coder/workspace:rw
      # 持久化 code-server 配置
      - ../../data/.code-server/config:/home/coder/.config:rw
      - ../../data/.code-server/data:/home/coder/.local/share/code-server:rw
    ports:
      - "${CODE_SERVER_PORT:-8443}:8000"
    # 开发模式：无需密码，绑定到 8000 端口
    command: ["--auth=none", "--disable-telemetry", "--bind-addr=0.0.0.0:8000"]
