# ML-Server-Manager Production Environment - Worker Node
# 生产模式：使用 Podman 运行 worker + code-server
# 为后续迁移 Kubernetes 做准备
#
# Usage (从项目根目录或复制到远程服务器):
#   podman-compose -f infra/prod/worker.yml up -d
#   make prod-worker  # 或使用 Makefile

services:
  # Worker Agent (Go)
  worker:
    build:
      context: ../../worker
      dockerfile: Dockerfile
    image: mlsmanager-worker:latest
    container_name: mlsm-worker
    restart: unless-stopped
    environment:
      AGENT_MASTER_URL: ${AGENT_MASTER_URL}
      AGENT_NODE_NAME: ${AGENT_NODE_NAME:-worker-001}
      AGENT_STORAGE_PATH: /data
      AGENT_DATASETS_PATH: /data/datasets
      AGENT_PROJECTS_PATH: /data/projects
      AGENT_TOKEN_FILE: /etc/ml-agent/token
    volumes:
      # 绑定挂载数据目录 (与 code-server 共享)
      - ../../data:/data:Z
      - ../../data/.ml-agent:/etc/ml-agent:Z
    user: "${UID:-1000}:${GID:-1000}"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Code-Server (VS Code in Browser)
  code-server:
    image: codercom/code-server:latest
    container_name: mlsm-codeserver
    restart: unless-stopped
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      PASSWORD: ${CODE_SERVER_PASSWORD}
      # 清除代理设置
      HTTP_PROXY: ""
      HTTPS_PROXY: ""
      http_proxy: ""
      https_proxy: ""
    volumes:
      # 挂载项目目录 (与 worker 共享)
      - ../../data/projects:/home/coder/workspace:Z
      # 持久化 code-server 配置
      - ../../data/.code-server/config:/home/coder/.config:Z
      - ../../data/.code-server/data:/home/coder/.local/share/code-server:Z
    ports:
      - "${CODE_SERVER_PORT:-8443}:8000"
    command: ["--auth=password", "--disable-telemetry"]
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 512M
